# Generated by Django 5.1.2 on 2024-10-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='quality_fiction',
            new_name='qualification',
        ),
    ]
