# Generated by Django 5.1.2 on 2024-10-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_teacher_department_alter_teacher_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
