# Generated by Django 5.1.2 on 2024-10-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_teacher_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_events',
            old_name='Type',
            new_name='type',
        ),
    ]
